name: Node.js CI/CD

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      # 1. Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Copy .env from your EC2 folder to the current workflow directory
      - name: Copy .env
        run: cp /home/ec2-user/node-streak/.env $PWD/.env

      # 5. Run tests (optional placeholder)
      - name: Run tests
        run: echo "No tests yet"

      # 6. Restart app with PM2
      - name: Restart PM2 app
        run: |
          APP_PATH="$PWD/src/server.js"
          echo "Starting app from: $APP_PATH"
          pm2 delete node-streak || true
          pm2 start $APP_PATH --name node-streak
          pm2 save
